name: "CI/CD Pipeline"
on: [pull_request, push]

jobs:
  setup-minikube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: opsgang/ga-setup-minikube@v0.1.2
      with:
        minikube-version: 1.21.0
        k8s-version: 1.20.7
    - name: Setup Cluster
      run: |
        minikube config set vm-driver docker
        minikube config set kubernetes-version v1.20.7
        minikube start
        minikube update-context
        minikube addons enable ingress
        minikube addons enable metrics-server
        kubectl cluster-info
        kubectl get pods -A
    - name: Build image 
      run: | 
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t adjust-ruby-app:latest .
        echo -n "verifying images:"
        docker images
    - name: Deploy to minikube
      run: 
        kubectl apply -f ruby-app-k8s.yaml && kubectl rollout status deployment adjust-ruby-app
    - name: Test service URLs
      run: | 
        echo -n "Testing Endpoint..."
        kubectl	get svc	adjust-ruby-app
        minikube ip
        curl -H "Host: ruby-app.adjust.local" http://$(minikube ip)
