name: "CI/CD Pipeline"
on: [pull_request, push]

jobs:
  setup-minikube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: opsgang/ga-setup-minikube@v0.1.2
      with:
        minikube-version: 1.21.0
        k8s-version: 1.20.7
    - name: Setup Cluster
      run: |
        minikube config set vm-driver docker
        minikube config set kubernetes-version v1.20.7
        minikube start
        minikube update-context
        kubectl cluster-info
        kubectl get pods -A
    - name: Build image 
      run: | 
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t adjust-ruby-app:latest .
        echo -n "verifying images:"
        docker images
    - name: Deploy to minikube
      run: 
        kubectl apply -f deploy/deploy-minikube.yaml
    - name: Test service URLs
      run: | 
        minikube service list
        minikube service discover --url
        echo -n "Testing Endpoint..."
        curl $(minikube service discover --url)/version
